### ISSUE TITLE
week-6

### ISSUE THREAD

**Issue by cadeaumarckenzy** [HtFacile/HtFacile#3]
1- 
finish with the wireframe with android studio

**Comment by cadeaumarckenzy** [comment]
ce soir je dois terminer avec!!!

**Comment by cadeaumarckenzy** [comment]
contribution par Peterson pour l'achevement de notre WIREFRAME!!!

**Comment by saintilien1** [comment]
I don't see the activity, Cadeau and Peterson what's happened? if you have a problem , please share it with me, or the bootcamp plateform.
